$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code:
  local_path: .
command: >-
  accelerate launch
  --config_file accelerate_config.yaml
  --machine_rank $NODE_RANK
  --main_process_ip $MASTER_ADDR
  --main_process_port $MASTER_PORT
  hf_nlp.py
environment:
  build:
    local_path: ./docker
compute: azureml:gpu-cluster-m60
distribution:
  type: pytorch
  process_count_per_instance: 1
resources:
  instance_count: 2
display_name: accelerate-distributed-example
experiment_name: accelerate-distributed-example
