name: pytorch-hf
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip:
      - accelerate==0.5.1
      - transformers
      - datasets
      - timm==0.4.12
      - toml==0.10.2
      - tomli==1.2.2
      - torchmetrics==0.6.0
      - tqdm==4.62.3

