version: v0.1.2

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - examples
    - requirements: docs/requirements_docs.txt

submodules:
  include: all
