version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Allow harmless warnings (like intersphinx network issues)

python:
  install:
    - path: .
    - requirements: docs/requirements_docs.txt

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

formats:
  - pdf
