version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true


python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
