version: 2
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
    - requirements: docs/requirements_docs.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

formats:
  - pdf
